@url = http://localhost:8080/api/country
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmaWVsZC1hZ2VudCIsInN1YiI6InVzZXJAZXhhbXBsZS5jb20iLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTc1NzYxNjAwNX0.eF1ygPAL5VKM2GVonf_27l77o_tshs6zn2ld0Foq4BI

### register

POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "user@example.com",
    "password": "Password123.",
    "firstName": "Test",
    "lastName": "Tester",
    "currencyId": 1
}

### login (get jwt token)

POST http://localhost:8080/api/auth/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "user@example.com",
    "password": "Password123."
}

### findAll

GET {{url}} HTTP/1.1
Authorization: Bearer {{token}}

### findById - happy path

GET {{url}}/1 HTTP/1.1
Authorization: Bearer {{token}}

### findById - unhappy path

GET {{url}}/999 HTTP/1.1
Authorization: Bearer {{token}}

### add - happy path

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "currency": {
        "name": "Japanese Yen",
        "code": "JPY",
        "valueToUsd": 0.0068
    },
    "name": "Japan",
    "code": "JPN"
}

### add - unhappy path (BAD REQUEST)

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{}

### update - happy path

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 2,
    "currency": {
        "name": "Japanese Yen",
        "code": "JPY",
        "valueToUsd": 0.0068
    },
    "name": "Japan",
    "code": "JPN"
}

### update - unhappy path (NOT FOUND)

PUT {{url}}/999 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 999,
    "currency": {
        "name": "Japanese Yen",
        "code": "JPY",
        "valueToUsd": 0.0068
    },
    "name": "Japan",
    "code": "JPN"
}

### update - unhappy path (CONFLICT)

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 1,
    "currency": {
        "name": "Japanese Yen",
        "code": "JPY",
        "valueToUsd": 0.0068
    },
    "name": "Japan",
    "code": "JPN"
}

### update - unhappy path (BAD REQUEST)

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 2,
    "currency": {
        "name": "Japanese Yen",
        "code": "JPY",
        "valueToUsd": 0.0068
    },
    "name": "",
    "code": "JPN"
}

### delete - happy path (run add request first for this to be happy path)

DELETE {{url}}/4 HTTP/1.1
Authorization: Bearer {{token}}

### delete - unhappy path (NOT FOUND)

DELETE {{url}}/999 HTTP/1.1
Authorization: Bearer {{token}}

### delete - unhappy path (BAD REQUEST)

DELETE {{url}}/1 HTTP/1.1
Authorization: Bearer {{token}}