@url = http://localhost:8080/api/order
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmaWVsZC1hZ2VudCIsInN1YiI6InVzZXJAZXhhbXBsZS5jb20iLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTc1NzYxNTI5Mn0.obeSURxNESdZpdZui95m6svfkVMbRLpMgCBo_jAJY-o

### register

POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "user@example.com",
    "password": "Password123."
}

### login (get jwt token)

POST http://localhost:8080/api/auth/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "user@example.com",
    "password": "Password123."
}

### findAll

GET {{url}} HTTP/1.1
Authorization: Bearer {{token}}

### findById - happy path

GET {{url}}/1 HTTP/1.1
Authorization: Bearer {{token}}

### findById - unhappy path

GET {{url}}/999 HTTP/1.1
Authorization: Bearer {{token}}

### findByStock

GET {{url}}/stock/7 HTTP/1.1
Authorization: Bearer {{token}}

### add - happy path

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "transactionType": "BUY",
    "stockId": 1,
    "numberOfShares": 10.0,
    "date": "2021-12-12",
    "price": 12.95
}

### add - unhappy path (BAD REQUEST)

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{}

### update - happy path

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 2,
    "transactionType": "SELL",
    "stockId": 1,
    "numberOfShares": 10.0,
    "date": "2021-12-12",
    "price": 12.95
}

### update - unhappy path (NOT FOUND)

PUT {{url}}/999 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 999,
    "transactionType": "SELL",
    "stockId": 1,
    "numberOfShares": 10.0,
    "date": "2021-12-12",
    "price": 12.95
}

### update - unhappy path  (CONFLICT)

PUT {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 2,
    "transactionType": "SELL",
    "stockId": 1,
    "numberOfShares": 10.0,
    "date": "2021-12-12",
    "price": 12.95
}

### update - unhappy path (BAD REQUEST)

PUT {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 1,
    "transactionType": "SELL",
    "stockId": 1,
    "numberOfShares": -10.0,
    "date": "2021-12-12",
    "price": 12.95
}

### delete - happy path

DELETE {{url}}/3 HTTP/1.1
Authorization: Bearer {{token}}

### delete - unhappy path (NOT FOUND)

DELETE {{url}}/999 HTTP/1.1
Authorization: Bearer {{token}}